POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhd255YSIsImlkIjoiNjkyYjY4NjJiNjM5M2YxNjY3ZWQ0MzlmIiwiaWF0IjoxNzY1MTU5MDg5LCJleHAiOjE3NjUxNjI2ODl9.eKt9r79-71R828xxi4Y_Z7ROd6sH0yaz9NoDm9bYYyI

{
    "title": "Tawnya's Blog3",
    "url": "tawnyaBlogURL3"
}